import {
  PDFDocument,
  StandardFonts,
  type PDFImage,
  type PDFPage,
  type PDFFont
} from "pdf-lib";

/** Binary data that can be obtained directly from a browser `File`. */
export type LocalBinary = ArrayBuffer | Uint8Array;

/** A local PNG or JPEG selected by the user. Nothing in this type is a URL. */
export interface LocalImageSource {
  bytes: LocalBinary;
  name: string;
  mimeType: string;
}

/** Text already available in memory, for example from a `<textarea>`. */
export interface PlainTextContent {
  text: string;
  name?: string;
  mimeType?: string;
}

/** A UTF-8 plain-text file selected in the browser. */
export interface PlainTextFileSource {
  bytes: LocalBinary;
  name: string;
  mimeType?: string;
}

/** Convenience input accepted by `createPdfFromText`. */
export type PlainTextSource = string | PlainTextContent | PlainTextFileSource;

export type PdfPageSizePreset = "a4" | "letter";

/** A page size in PDF points (72 points = 1 inch). */
export interface CustomPdfPageSize {
  width: number;
  height: number;
}

export type PdfPageSize = PdfPageSizePreset | CustomPdfPageSize;
export type PdfPageOrientation = "portrait" | "landscape";
export type ImagePageOrientation = PdfPageOrientation | "auto";
export type ImageFit = "contain" | "cover";

interface CommonPdfOptions {
  /** `a4` by default. Custom dimensions are expressed in PDF points. */
  pageSize?: PdfPageSize;
  /** Empty space around content in PDF points. Defaults to 36 (half an inch). */
  margin?: number;
  /** Suggested filename returned with the generated bytes. The `.pdf` suffix is added when absent. */
  fileName?: string;
  /** PDF document title. It is metadata only and does not alter visible content. */
  title?: string;
}

export interface ImagesToPdfOptions extends CommonPdfOptions {
  /**
   * Page orientation for every image. `auto` (the default) follows each
   * image's aspect ratio, so a document may contain both portrait and
   * landscape pages.
   */
  orientation?: ImagePageOrientation;
  /** `contain` keeps the full image visible; `cover` fills the printable area. */
  fit?: ImageFit;
}

export interface TextToPdfOptions extends CommonPdfOptions {
  /** Portrait is the default because text normally reads vertically. */
  orientation?: PdfPageOrientation;
  /** Font size in PDF points. Defaults to 12. */
  fontSize?: number;
  /** Distance between baselines in PDF points. Defaults to 1.4 × font size. */
  lineHeight?: number;
}

/** A self-contained, locally generated PDF ready for the existing download helper. */
export interface PdfConversionResult {
  bytes: Uint8Array;
  name: string;
  mimeType: "application/pdf";
  pageCount: number;
}

const A4: CustomPdfPageSize = { width: 595.28, height: 841.89 };
const LETTER: CustomPdfPageSize = { width: 612, height: 792 };
const DEFAULT_MARGIN = 36;
const MIN_PAGE_EDGE = 72;
const MAX_PAGE_EDGE = 14_400;
const MIN_CONTENT_EDGE = 12;

/**
 * Creates a brand-new local PDF with one source image per page.
 *
 * Only PNG and JPEG are deliberately supported because pdf-lib can embed
 * them in-browser without a server-side converter. The returned bytes do not
 * upload or mutate the source image buffers.
 */
export async function createPdfFromImages(
  images: readonly LocalImageSource[],
  options: ImagesToPdfOptions = {}
): Promise<PdfConversionResult> {
  if (!Array.isArray(images) || images.length === 0) {
    throw new Error("Selecciona al menos una imagen PNG o JPEG para crear el PDF.");
  }

  const pageSize = resolvePageSize(options.pageSize);
  const margin = resolveMargin(options.margin, pageSize);
  const orientation = resolveImageOrientation(options.orientation);
  const fit = resolveImageFit(options.fit);
  const preparedImages = images.map((image, index) => prepareImage(image, index));

  const document = await PDFDocument.create();
  const title = resolveTitle(options.title, "Imágenes convertidas");
  applyOutputMetadata(document, title);

  for (const imageSource of preparedImages) {
    const image = await embedImage(document, imageSource);
    const dimensions = orientPage(pageSize, orientation === "auto"
      ? image.width > image.height ? "landscape" : "portrait"
      : orientation);
    const page = document.addPage([dimensions.width, dimensions.height]);
    drawFittedImage(page, image, margin, fit);
  }

  const bytes = await savePdf(document);
  return {
    bytes,
    name: resolvePdfFileName(options.fileName, "imagenes-convertidas.pdf"),
    mimeType: "application/pdf",
    pageCount: preparedImages.length
  };
}

/**
 * Converts UTF-8 plain text to a fresh local PDF. It accepts a string from a
 * text area as well as a browser-file shaped object containing bytes, name and
 * MIME type. Text is wrapped to the printable width and flows onto new pages.
 */
export async function createPdfFromText(
  input: PlainTextSource,
  options: TextToPdfOptions = {}
): Promise<PdfConversionResult> {
  const textSource = readPlainText(input);
  const pageSize = resolvePageSize(options.pageSize);
  const orientation = resolveTextOrientation(options.orientation);
  const dimensions = orientPage(pageSize, orientation);
  const margin = resolveMargin(options.margin, dimensions);
  const fontSize = resolveFontSize(options.fontSize);
  const lineHeight = resolveLineHeight(options.lineHeight, fontSize);

  const document = await PDFDocument.create();
  const title = resolveTitle(options.title, baseName(textSource.name) || "Texto convertido");
  applyOutputMetadata(document, title);

  let font: PDFFont;
  try {
    font = await document.embedFont(StandardFonts.Helvetica);
  } catch {
    throw new Error("No pudimos preparar la fuente local necesaria para crear el PDF.");
  }

  const printableWidth = dimensions.width - margin * 2;
  let lines: string[];
  try {
    lines = wrapPlainText(textSource.text, font, fontSize, printableWidth);
  } catch {
    throw new Error("El texto contiene caracteres que la fuente local no puede representar. Guarda el archivo como texto UTF-8 simple e inténtalo de nuevo.");
  }

  let page: PDFPage | undefined;
  let cursorY = 0;
  let pageCount = 0;
  const newPage = (): void => {
    page = document.addPage([dimensions.width, dimensions.height]);
    cursorY = dimensions.height - margin - fontSize;
    pageCount += 1;
  };

  for (const line of lines) {
    if (!page || cursorY < margin) newPage();
    const targetPage = page;
    if (!targetPage) {
      throw new Error("No pudimos preparar una página para el texto.");
    }
    if (line) {
      try {
        targetPage.drawText(line, { x: margin, y: cursorY, size: fontSize, font });
      } catch {
        throw new Error("No pudimos escribir una parte del texto en el PDF. Revisa que el contenido sea texto UTF-8 simple.");
      }
    }
    cursorY -= lineHeight;
  }

  const bytes = await savePdf(document);
  return {
    bytes,
    name: resolvePdfFileName(options.fileName, `${baseName(textSource.name) || "texto"}-convertido.pdf`),
    mimeType: "application/pdf",
    pageCount
  };
}

interface PreparedImage {
  bytes: Uint8Array;
  name: string;
  format: "png" | "jpeg";
}

function prepareImage(input: LocalImageSource, index: number): PreparedImage {
  if (!input || typeof input !== "object") {
    throw new Error(`La imagen ${index + 1} no es válida. Selecciona un archivo PNG o JPEG.`);
  }

  const name = resolveSourceName(input.name, `imagen-${index + 1}`);
  const bytes = cloneBytes(input.bytes, `La imagen «${name}» está vacía o no se pudo leer.`);
  const detectedFormat = detectImageFormat(bytes);
  const declaredFormat = resolveImageMimeType(input.mimeType, name);
  if (declaredFormat && detectedFormat && declaredFormat !== detectedFormat) {
    throw new Error(`El tipo declarado de «${name}» no coincide con su contenido. Vuelve a seleccionar la imagen original.`);
  }
  if (!detectedFormat) {
    throw new Error(`No pudimos reconocer «${name}» como una imagen PNG o JPEG válida.`);
  }

  return { bytes, name, format: detectedFormat };
}

async function embedImage(document: PDFDocument, image: PreparedImage): Promise<PDFImage> {
  try {
    return image.format === "png"
      ? await document.embedPng(image.bytes)
      : await document.embedJpg(image.bytes);
  } catch {
    throw new Error(`No pudimos leer la imagen «${image.name}». El archivo puede estar dañado o usar un formato no compatible.`);
  }
}

function drawFittedImage(page: PDFPage, image: PDFImage, margin: number, fit: ImageFit): void {
  const availableWidth = page.getWidth() - margin * 2;
  const availableHeight = page.getHeight() - margin * 2;
  const scale = fit === "cover"
    ? Math.max(availableWidth / image.width, availableHeight / image.height)
    : Math.min(availableWidth / image.width, availableHeight / image.height);
  const width = image.width * scale;
  const height = image.height * scale;
  page.drawImage(image, {
    x: (page.getWidth() - width) / 2,
    y: (page.getHeight() - height) / 2,
    width,
    height
  });
}

function readPlainText(input: PlainTextSource): PlainTextContent {
  if (typeof input === "string") {
    return validatePlainText(input, "texto.txt", undefined);
  }
  if (!input || typeof input !== "object") {
    throw new Error("Selecciona texto plano o escribe contenido antes de crear el PDF.");
  }

  if ("text" in input) {
    return validatePlainText(input.text, input.name, input.mimeType);
  }

  const name = resolveSourceName(input.name, "texto.txt");
  assertPlainTextMimeType(input.mimeType, name);
  const bytes = cloneBytes(input.bytes, `El archivo «${name}» está vacío o no se pudo leer.`);
  let text: string;
  try {
    text = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    throw new Error(`No pudimos leer «${name}» como texto UTF-8. Guarda el archivo como .txt UTF-8 e inténtalo de nuevo.`);
  }
  return validatePlainText(text, name, input.mimeType);
}

function validatePlainText(text: unknown, name: string | undefined, mimeType: string | undefined): PlainTextContent {
  const sourceName = resolveSourceName(name, "texto.txt");
  assertPlainTextMimeType(mimeType, sourceName);
  if (typeof text !== "string" || !text.trim()) {
    throw new Error("El texto está vacío. Escribe o selecciona contenido antes de crear el PDF.");
  }
  return { text: text.replace(/\r\n?/g, "\n"), name: sourceName, mimeType };
}

function wrapPlainText(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
  const lines: string[] = [];
  for (const paragraph of text.split("\n")) {
    if (!paragraph) {
      lines.push("");
      continue;
    }

    let currentLine = "";
    for (const token of paragraph.match(/\S+\s*/g) ?? []) {
      const candidate = `${currentLine}${token}`;
      if (currentLine && font.widthOfTextAtSize(candidate.trimEnd(), fontSize) > maxWidth) {
        lines.push(currentLine.trimEnd());
        currentLine = token.trimStart();
      } else {
        currentLine = candidate;
      }

      while (font.widthOfTextAtSize(currentLine.trimEnd(), fontSize) > maxWidth) {
        const splitAt = fittingCharacterCount(currentLine.trimEnd(), font, fontSize, maxWidth);
        lines.push(currentLine.slice(0, splitAt));
        currentLine = currentLine.slice(splitAt).trimStart();
      }
    }
    if (currentLine.trimEnd()) lines.push(currentLine.trimEnd());
  }
  return lines;
}

function fittingCharacterCount(value: string, font: PDFFont, fontSize: number, maxWidth: number): number {
  let low = 1;
  let high = value.length;
  let best = 1;
  while (low <= high) {
    const middle = Math.floor((low + high) / 2);
    if (font.widthOfTextAtSize(value.slice(0, middle), fontSize) <= maxWidth) {
      best = middle;
      low = middle + 1;
    } else {
      high = middle - 1;
    }
  }
  return best;
}

function resolvePageSize(value: PdfPageSize | undefined): CustomPdfPageSize {
  if (value === undefined || value === "a4") return { ...A4 };
  if (value === "letter") return { ...LETTER };
  if (!value || typeof value !== "object" || !isValidPageEdge(value.width) || !isValidPageEdge(value.height)) {
    throw new Error(`El tamaño de página debe tener ancho y alto entre ${MIN_PAGE_EDGE} y ${MAX_PAGE_EDGE} puntos.`);
  }
  return { width: value.width, height: value.height };
}

function orientPage(size: CustomPdfPageSize, orientation: PdfPageOrientation): CustomPdfPageSize {
  const shortEdge = Math.min(size.width, size.height);
  const longEdge = Math.max(size.width, size.height);
  return orientation === "landscape"
    ? { width: longEdge, height: shortEdge }
    : { width: shortEdge, height: longEdge };
}

function resolveMargin(value: number | undefined, pageSize: CustomPdfPageSize): number {
  const margin = value ?? DEFAULT_MARGIN;
  const maximumMargin = (Math.min(pageSize.width, pageSize.height) - MIN_CONTENT_EDGE) / 2;
  if (!Number.isFinite(margin) || margin < 0 || margin > maximumMargin) {
    throw new Error(`El margen debe estar entre 0 y ${formatPoints(maximumMargin)} puntos para este tamaño de página.`);
  }
  return margin;
}

function resolveImageOrientation(value: ImagePageOrientation | undefined): ImagePageOrientation {
  if (value === undefined || value === "auto" || value === "portrait" || value === "landscape") return value ?? "auto";
  throw new Error("La orientación de imagen debe ser automática, vertical u horizontal.");
}

function resolveTextOrientation(value: PdfPageOrientation | undefined): PdfPageOrientation {
  if (value === undefined || value === "portrait" || value === "landscape") return value ?? "portrait";
  throw new Error("La orientación del texto debe ser vertical u horizontal.");
}

function resolveImageFit(value: ImageFit | undefined): ImageFit {
  if (value === undefined || value === "contain" || value === "cover") return value ?? "contain";
  throw new Error("El ajuste de imagen debe ser «contain» o «cover».");
}

function resolveFontSize(value: number | undefined): number {
  const fontSize = value ?? 12;
  if (!Number.isFinite(fontSize) || fontSize < 4 || fontSize > 72) {
    throw new Error("El tamaño de letra debe estar entre 4 y 72 puntos.");
  }
  return fontSize;
}

function resolveLineHeight(value: number | undefined, fontSize: number): number {
  const lineHeight = value ?? fontSize * 1.4;
  if (!Number.isFinite(lineHeight) || lineHeight < fontSize || lineHeight > 144) {
    throw new Error("La altura de línea debe ser igual o mayor que el tamaño de letra y no superar 144 puntos.");
  }
  return lineHeight;
}

function resolveImageMimeType(value: unknown, name: string): "png" | "jpeg" | undefined {
  const mime = typeof value === "string" ? value.split(";", 1)[0]?.trim().toLowerCase() : "";
  if (mime === "image/png") return "png";
  if (mime === "image/jpeg" || mime === "image/jpg") return "jpeg";
  // Browsers are allowed to leave File.type empty. The binary signature still
  // lets us identify a PNG/JPEG without trusting a filename extension.
  if (!mime || mime === "application/octet-stream") return undefined;
  throw new Error(`«${name}» no es PNG ni JPEG. Este conversor local solo admite imágenes PNG y JPEG.`);
}

function assertPlainTextMimeType(value: unknown, name: string): void {
  if (value === undefined || value === null || value === "") return;
  const mime = typeof value === "string" ? value.split(";", 1)[0]?.trim().toLowerCase() : "";
  if (mime !== "text/plain") {
    throw new Error(`«${name}» no es texto plano. Selecciona un archivo .txt UTF-8.`);
  }
}

function detectImageFormat(bytes: Uint8Array): "png" | "jpeg" | undefined {
  const isPng = bytes.byteLength >= 8
    && bytes[0] === 0x89
    && bytes[1] === 0x50
    && bytes[2] === 0x4e
    && bytes[3] === 0x47
    && bytes[4] === 0x0d
    && bytes[5] === 0x0a
    && bytes[6] === 0x1a
    && bytes[7] === 0x0a;
  if (isPng) return "png";
  const isJpeg = bytes.byteLength >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff;
  return isJpeg ? "jpeg" : undefined;
}

function cloneBytes(value: unknown, emptyError: string): Uint8Array {
  let bytes: Uint8Array;
  // A File may have been created in a different browser realm (for example a
  // preview iframe), where `instanceof Uint8Array` is false. The tag keeps the
  // public contract strict while still accepting that normal browser case.
  if (isUint8Array(value)) {
    bytes = new Uint8Array(value.byteLength);
    bytes.set(new Uint8Array(value.buffer, value.byteOffset, value.byteLength));
  } else if (isArrayBuffer(value)) {
    bytes = new Uint8Array(value.slice(0));
  } else {
    throw new Error(emptyError);
  }
  if (bytes.byteLength === 0) throw new Error(emptyError);
  return bytes;
}

function resolveSourceName(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function resolveTitle(value: unknown, fallback: string): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function resolvePdfFileName(value: unknown, fallback: string): string {
  const candidate = typeof value === "string" && value.trim() ? value.trim() : fallback;
  const withoutPath = candidate.replace(/[\\/:*?"<>|\u0000-\u001f]/g, "-").replace(/\.+$/g, "");
  const safe = withoutPath || fallback;
  return /\.pdf$/i.test(safe) ? safe : `${safe}.pdf`;
}

function baseName(value: string | undefined): string {
  if (!value) return "";
  return value.replace(/\.[^.]+$/, "").trim();
}

function applyOutputMetadata(document: PDFDocument, title: string): void {
  document.setTitle(title);
  document.setCreator("Free PDF");
  document.setProducer("Free PDF");
}

async function savePdf(document: PDFDocument): Promise<Uint8Array> {
  try {
    return await document.save({ useObjectStreams: true, addDefaultPage: false });
  } catch {
    throw new Error("No pudimos crear el PDF local resultante. Inténtalo de nuevo.");
  }
}

function isValidPageEdge(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value >= MIN_PAGE_EDGE && value <= MAX_PAGE_EDGE;
}

function isUint8Array(value: unknown): value is Uint8Array {
  return Object.prototype.toString.call(value) === "[object Uint8Array]";
}

function isArrayBuffer(value: unknown): value is ArrayBuffer {
  return Object.prototype.toString.call(value) === "[object ArrayBuffer]";
}

function formatPoints(value: number): string {
  return new Intl.NumberFormat("es", { maximumFractionDigits: 1 }).format(value);
}
