/** Downloads generated bytes without sending them to a remote service. */
export function downloadBlob(bytes: Uint8Array, name: string, mimeType: string): void {
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
  const url = URL.createObjectURL(new Blob([buffer], { type: mimeType }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = name;
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1_000);
}

export function downloadPdf(bytes: Uint8Array, name: string): void {
  downloadBlob(bytes, name.endsWith(".pdf") ? name : `${name}.pdf`, "application/pdf");
}
